#exec-once = swaybg -c 000000

preload = /home/aac-lap/Downloads/wallpaper.jpg
#wallpaper = HDMI-A-1,/home/youruser/Pictures/wallpaper.png
wallpaper = eDP-1, /home/aac-lap/Downloads/wallpaper.jpg
# wallpaper = HDMI-A-2,/home/youruser/Pictures/wallpaper.png
