return{}
-- return {
-- 	"rmagatti/auto-session",
-- 	config = function()
-- 		require("auto-session").setup({
-- 			auto_restore_enable = false,
-- 			auto_session_supress_dirs = { "~/", "~/Downloads" },
-- 		})
--
-- 		vim.keymap.set("n", "<leader>so", "<cmd>SessionRestore<CR>", { desc = "Restore session for cwd" })
-- 		vim.keymap.set("n", "<leader>ss", "<cmd>SessionSave<CR>", { desc = "Save session for auto session root dir" })
-- 	end,
-- }
